In [1]:
import pandas as pd
import numpy as np

In [2]:
df= pd.read_csv("churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df["Dependents"].dtype

dtype('O')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [11]:
df["TotalCharges"]=pd.to_numeric(df["TotalCharges"],errors="coerce")

In [17]:
df[df["TotalCharges"].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

In [18]:
df.dropna(subset="TotalCharges",inplace=True)

In [20]:
df.drop("customerID",axis = 1 ,inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7032 non-null   object
 1   SeniorCitizen     7032 non-null   int64
 2   Partner           7032 non-null   object
 3   Dependents        7032 non-null   object
 4   tenure            7032 non-null   int64
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  Contract          7032 non-null   object
 15  PaperlessBilling  7032 non-null   object
 16  PaymentMethod     7032 non-null   object
 17  MonthlyCharges    7032 non-null   float64
 18  TotalCharges      7032 non-null   float64
 19  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(16)
memory usage: 1.1+ MB

In [22]:
df["Churn"].value_counts()

No     5163
Yes    1869
Name: Churn, dtype: int64

In [ ]:
# aws connection

In [4]:
import os 
import boto3
import sys

In [30]:
aws_acces_key = "AWS_ACCESS_KEY_ID"
aws_secret_access = "AWS_SECRET_ACCESS_KEY"
region = "eu-north-1"

In [31]:
boto = boto3.client("s3", 
                    aws_access_key_id = os.getenv(aws_acces_key),
                    aws_secret_access_key = os.getenv(aws_secret_access),
                    region_name = region)

In [11]:
response = boto.list_buckets()

In [12]:
response

{'ResponseMetadata': {'RequestId': '0CZJPVGNC3SSZGC9',
  'HostId': '+/2QRgaflg8tJccq9iBpxEM/qdp008yCuhvCZNlP9LfYqWJPx/BybDkmOECiuPiGkbQyudY13Z//byCS8d7QIPrhJ7D7GyDe',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': '+/2QRgaflg8tJccq9iBpxEM/qdp008yCuhvCZNlP9LfYqWJPx/BybDkmOECiuPiGkbQyudY13Z//byCS8d7QIPrhJ7D7GyDe',
   'x-amz-request-id': '0CZJPVGNC3SSZGC9',
   'date': 'Sat, 06 Jun 2026 03:18:09 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'visaprojectbucket',
   'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}],
 'Owner': {'ID': 'd683345c1b8fbbc864f9449fc07735fd167043d4c55db5412d2b504596d0725b'}}

In [21]:
for bucket in response["Buckets"]:

    print(bucket["Name"])

visaprojectbucket

In [40]:
boto.create_bucket(Bucket = "churnprojectbucket",CreateBucketConfiguration = {"LocationConstraint":region})

{'ResponseMetadata': {'RequestId': 'ZWB6X94JYQNB1BCK',
  'HostId': 'aoK2uYMoDeChfbSiapNxhPOSOW4MwxiY8lxuGvsYOa2+5a5NOklTWhc3iMvZZM13ATPyqJA+kZ5jZtNHiN+esfn3lb8WWCx6',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'aoK2uYMoDeChfbSiapNxhPOSOW4MwxiY8lxuGvsYOa2+5a5NOklTWhc3iMvZZM13ATPyqJA+kZ5jZtNHiN+esfn3lb8WWCx6',
   'x-amz-request-id': 'ZWB6X94JYQNB1BCK',
   'date': 'Sat, 06 Jun 2026 03:47:34 GMT',
   'location': 'http://churnprojectbucket.s3.amazonaws.com/',
   'x-amz-bucket-arn': 'arn:aws:s3:::churnprojectbucket',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Location': 'http://churnprojectbucket.s3.amazonaws.com/'}

In [41]:
buckets = boto.list_buckets()

In [42]:
buckets

{'ResponseMetadata': {'RequestId': '8929ZKY6WTEZYQE3',
  'HostId': 'wQTHFfW5W1rh2RK1yhfksiVdP75PlChOjA31iZjLN99ilssuPTcfh5zTvJWMYjxPjGOspqJVbTUpaEklONz1kupLTwDM0aHO',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'wQTHFfW5W1rh2RK1yhfksiVdP75PlChOjA31iZjLN99ilssuPTcfh5zTvJWMYjxPjGOspqJVbTUpaEklONz1kupLTwDM0aHO',
   'x-amz-request-id': '8929ZKY6WTEZYQE3',
   'date': 'Sat, 06 Jun 2026 03:48:18 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'churnprojectbucket',
   'CreationDate': datetime.datetime(2026, 6, 6, 3, 47, 34, tzinfo=tzutc())},
  {'Name': 'visaprojectbucket',
   'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}],
 'Owner': {'ID': 'd683345c1b8fbbc864f9449fc07735fd167043d4c55db5412d2b504596d0725b'}}

In [43]:
for bucket in buckets["Buckets"]:

    print(bucket["Name"])

churnprojectbucket
visaprojectbucket

In [55]:
from from_root import from_root

In [57]:
boto.upload_file("churn.csv","visaprojectbucket","data/cutomer.csv")

In [71]:
obj = boto.list_objects_v2(Bucket =  "visaprojectbucket")

In [72]:
obj

{'ResponseMetadata': {'RequestId': 'HSPAMTTKPYY8A286',
  'HostId': 'wSOV6CqaJ1h3oe8Sdfsd8yeEScwsZzToEwH5PrjYT6klwsvavG74dPbSmO5D0Iy++3G2eGtKCd0JL28PgcSkpY5YtPELJiZS',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'wSOV6CqaJ1h3oe8Sdfsd8yeEScwsZzToEwH5PrjYT6klwsvavG74dPbSmO5D0Iy++3G2eGtKCd0JL28PgcSkpY5YtPELJiZS',
   'x-amz-request-id': 'HSPAMTTKPYY8A286',
   'date': 'Sat, 06 Jun 2026 04:07:36 GMT',
   'x-amz-bucket-region': 'eu-north-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'IsTruncated': False,
 'Contents': [{'Key': 'data/cutomer.csv',
   'LastModified': datetime.datetime(2026, 6, 6, 4, 1, 29, tzinfo=tzutc()),
   'ETag': '"0f9de68e012bd3aed5fa7cdc9fc421af"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'Size': 977501,
   'StorageClass': 'STANDARD'},
  {'Key': 'model.pkl',
   'LastModified': datetime.datetime(2026, 5, 20, 3, 48, 6, tzinfo=tzutc()),
   'ETag': '"770e1362243aca1fe62335cb09fe18f4"',
   'ChecksumAlgorithm': ['CRC32'],
   'Size': 5261,
   'StorageClass': 'STANDARD'}],
 'Name': 'visaprojectbucket',
 'Prefix': '',
 'MaxKeys': 1000,
 'EncodingType': 'url',
 'KeyCount': 2}

In [73]:
obj["Contents"]

[{'Key': 'data/cutomer.csv',
  'LastModified': datetime.datetime(2026, 6, 6, 4, 1, 29, tzinfo=tzutc()),
  'ETag': '"0f9de68e012bd3aed5fa7cdc9fc421af"',
  'ChecksumAlgorithm': ['CRC64NVME'],
  'Size': 977501,
  'StorageClass': 'STANDARD'},
 {'Key': 'model.pkl',
  'LastModified': datetime.datetime(2026, 5, 20, 3, 48, 6, tzinfo=tzutc()),
  'ETag': '"770e1362243aca1fe62335cb09fe18f4"',
  'ChecksumAlgorithm': ['CRC32'],
  'Size': 5261,
  'StorageClass': 'STANDARD'}]

In [74]:
for ob in obj["Contents"]:

    print(ob["Key"])

data/cutomer.csv
model.pkl

In [76]:
boto.download_file("visaprojectbucket","data/cutomer.csv","downloaded_churn.csv")

In [77]:
boto.delete_object(
    Bucket = "visaprojectbucket",
    Key = "data/cutomer.csv"
)

{'ResponseMetadata': {'RequestId': 'EEP6Y0B4DH3TZ4T4',
  'HostId': 'bMBS901b5vnxGXyeTyDIqyAe4eTXvL2IVnjEDSjqD45rFhhjW7Xdm1Qipvuas5wNFC3PzctrbR0=',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': 'bMBS901b5vnxGXyeTyDIqyAe4eTXvL2IVnjEDSjqD45rFhhjW7Xdm1Qipvuas5wNFC3PzctrbR0=',
   'x-amz-request-id': 'EEP6Y0B4DH3TZ4T4',
   'date': 'Sat, 06 Jun 2026 04:13:49 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}

In [78]:
boto.delete_bucket(Bucket = "churnprojectbucket")

{'ResponseMetadata': {'RequestId': '99355YSYA63HPNFK',
  'HostId': '+y7JwNcqrJzYOUlL9r9cd2eq4H5e8LlhyvN/s+3SGi3FmkPswaEMA/OXhlIu5/5ITIRkvpifxSw=',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': '+y7JwNcqrJzYOUlL9r9cd2eq4H5e8LlhyvN/s+3SGi3FmkPswaEMA/OXhlIu5/5ITIRkvpifxSw=',
   'x-amz-request-id': '99355YSYA63HPNFK',
   'date': 'Sat, 06 Jun 2026 04:14:33 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}

In [1]:
aws_acces_key = "AWS_ACCESS_KEY_ID"
aws_secret_access = "AWS_SECRET_ACCESS_KEY"
region = "eu-north-1"

In [5]:
import boto3
import os

In [ ]:
s3 : boto3.client = boto3.client("s3",aws_access_key_id = os.getenv(aws_acces_key),
                  aws_secret_access_key = os.getenv(aws_secret_access),
                  region_name = region)

In [14]:
# create bucket 
s3.create_bucket(Bucket = "futureprojectbucket",CreateBucketConfiguration = {"LocationConstraint":region})

{'ResponseMetadata': {'RequestId': '33SCKEYHQ4X6T3A7',
  'HostId': 'tf346TXgdSXOYQEVnmQyecZYs8Dd+xIvNeDsbGjPEU9nZMPtKuyTYyb6fz1cUTPpgu0NEkMzpD8=',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'tf346TXgdSXOYQEVnmQyecZYs8Dd+xIvNeDsbGjPEU9nZMPtKuyTYyb6fz1cUTPpgu0NEkMzpD8=',
   'x-amz-request-id': '33SCKEYHQ4X6T3A7',
   'date': 'Sun, 07 Jun 2026 05:58:38 GMT',
   'location': 'http://futureprojectbucket.s3.amazonaws.com/',
   'x-amz-bucket-arn': 'arn:aws:s3:::futureprojectbucket',
   'content-length': '0',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Location': 'http://futureprojectbucket.s3.amazonaws.com/'}

In [15]:
list_buckets = s3.list_buckets()

In [ ]:
list_buckets

{'ResponseMetadata': {'RequestId': 'KAQQEQRVH6TRJZYJ',
  'HostId': 'lX4UuvhwXSNslO5pHwlTvj4N/GWWbPplkgVA6t5/rBLiL1tQPHyEFXeN92alG4jFiM8UUNtpktO/hQXrveg1IXc7IBsl9UON',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'lX4UuvhwXSNslO5pHwlTvj4N/GWWbPplkgVA6t5/rBLiL1tQPHyEFXeN92alG4jFiM8UUNtpktO/hQXrveg1IXc7IBsl9UON',
   'x-amz-request-id': 'KAQQEQRVH6TRJZYJ',
   'date': 'Sun, 07 Jun 2026 05:59:44 GMT',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'Buckets': [{'Name': 'churnprojectbucket',
   'CreationDate': datetime.datetime(2026, 6, 6, 6, 40, 39, tzinfo=tzutc())},
  {'Name': 'futureprojectbucket',
   'CreationDate': datetime.datetime(2026, 6, 7, 5, 58, 38, tzinfo=tzutc())},
  {'Name': 'visaprojectbucket',
   'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}],
 'Owner': {'ID': 'd683345c1b8fbbc864f9449fc07735fd167043d4c55db5412d2b504596d0725b'}}

In [45]:
list_buckets["ResponseMetadata"]["HTTPHeaders"]["content-type"].upper()

'APPLICATION/XML'

In [48]:
list_buckets["Buckets"][0]["Name"]

'churnprojectbucket'

In [53]:
for i in list_buckets["Buckets"]:

    print(i["CreationDate"])

2026-06-06 06:40:39+00:00
2026-06-07 05:58:38+00:00
2026-05-18 07:13:20+00:00

In [49]:
list_buckets["Buckets"]

[{'Name': 'churnprojectbucket',
  'CreationDate': datetime.datetime(2026, 6, 6, 6, 40, 39, tzinfo=tzutc())},
 {'Name': 'futureprojectbucket',
  'CreationDate': datetime.datetime(2026, 6, 7, 5, 58, 38, tzinfo=tzutc())},
 {'Name': 'visaprojectbucket',
  'CreationDate': datetime.datetime(2026, 5, 18, 7, 13, 20, tzinfo=tzutc())}]

In [61]:
is_present = [i for i in list_buckets["Buckets"] if i["Name"]=="churnprojectbuket"]

In [65]:
from botocore.exceptions import ClientError

In [67]:
try:
    s3.head_bucket(Bucket = "churnprojectbucke")

except ClientError as e:

    print(e.response["Error"])

{'Code': '404', 'Message': 'Not Found'}

In [ ]:
is_present = True

try:

    s3.head_bucket(Bucket = "churnprojtbucket")

    print("Bucket Exists")

    is_present = True

except ClientError as e:

    is_present = False


    response = e.response["Error"]["Code"]

    if response=='404':

        print(f"Busked not exists got {response}")
    
    elif response=='403':

        print("Bucket exists but access denied")

Busked not exists got 404

In [ ]:
is_present

False

In [77]:
%pwd

'd:\\AIML_Projects\\Churn_Customer_Prediction\\notebook'

In [78]:
os.chdir("../")

In [79]:
%pwd

'd:\\AIML_Projects\\Churn_Customer_Prediction'

In [80]:
# upload a file to bucket 
from testing import student

In [81]:
s3.upload_file("custom.pkl","futureprojectbucket","file")

In [82]:
s3.download_file("futureprojectbucket","file","custom(1).pkl")

In [ ]:
# load file directly into memory 
res = s3.get_object(Bucket = "futureprojectbucket",Key = "file")

In [96]:
res

{'ResponseMetadata': {'RequestId': '2XEDG6839Z5S8XAV',
  'HostId': 'ae2JssI0Vr8iLFX05k0CpfFLdalPVm61O5ACbfHePPZFBIUmPPQHbFP6GppcGnBl06jJ1btmIxHBuSyw+atr5H3HnzULskkf',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'ae2JssI0Vr8iLFX05k0CpfFLdalPVm61O5ACbfHePPZFBIUmPPQHbFP6GppcGnBl06jJ1btmIxHBuSyw+atr5H3HnzULskkf',
   'x-amz-request-id': '2XEDG6839Z5S8XAV',
   'date': 'Sun, 07 Jun 2026 06:56:10 GMT',
   'last-modified': 'Sun, 07 Jun 2026 06:34:57 GMT',
   'etag': '"09b2ac1a40440b593229eaca43ea77cc"',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'binary/octet-stream',
   'content-length': '66',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 6, 7, 6, 34, 57, tzinfo=tzutc()),
 'ContentLength': 66,
 'ETag': '"09b2ac1a40440b593229eaca43ea77cc"',
 'ContentType': 'binary/octet-stream',
 'ServerSideEncryption': 'AES256',
 'Metadata': {},
 'Body': <botocore.response.StreamingBody at 0x1a61f90b4c0>}

In [89]:
import io
import joblib

In [97]:
file_content = res["Body"].read()

In [98]:
file_content

b'\x80\x04\x957\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x07student\x94\x93\x94)\x81\x94}\x94(\x8c\x04name\x94\x8c\x05ashok\x94\x8c\x03age\x94K\x08ub.'

In [106]:
joblib.load(io.BytesIO(file_content)).age

8

In [107]:
future_bucket = s3.list_objects_v2(Bucket = "futureprojectbucket")

In [108]:
future_bucket

{'ResponseMetadata': {'RequestId': '6DBB977D5HDV2GVQ',
  'HostId': 'R9tEBhsKOJaIxEcmf3zR6pndd/SBQCopO+e3FnzK/nXevc2CS6KJz8YoagbU4bzuyNFdcfjk/qCGT2WOinfIjrTZcA/+gVqJ',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'R9tEBhsKOJaIxEcmf3zR6pndd/SBQCopO+e3FnzK/nXevc2CS6KJz8YoagbU4bzuyNFdcfjk/qCGT2WOinfIjrTZcA/+gVqJ',
   'x-amz-request-id': '6DBB977D5HDV2GVQ',
   'date': 'Sun, 07 Jun 2026 07:00:45 GMT',
   'x-amz-bucket-region': 'eu-north-1',
   'content-type': 'application/xml',
   'transfer-encoding': 'chunked',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'IsTruncated': False,
 'Contents': [{'Key': 'file',
   'LastModified': datetime.datetime(2026, 6, 7, 6, 34, 57, tzinfo=tzutc()),
   'ETag': '"09b2ac1a40440b593229eaca43ea77cc"',
   'ChecksumAlgorithm': ['CRC64NVME'],
   'Size': 66,
   'StorageClass': 'STANDARD'}],
 'Name': 'futureprojectbucket',
 'Prefix': '',
 'MaxKeys': 1000,
 'EncodingType': 'url',
 'KeyCount': 1}

In [110]:
for obj in future_bucket["Contents"]:

    print(obj["Key"])

file

In [115]:
files = [file["Key"] for file in future_bucket["Contents"] if file["Key"]=="file"]

In [116]:
files

['file']

In [125]:
is_present = True

try:

    s3.head_object(Bucket = "futureprojectbucket", Key = "file")

    print("file is present in bucket")


except ClientError as e:

    is_present = False

    res = e.response["Error"]["Code"]

    if res == "404":

        print("file not exists in bucket")
    
    else:

        raise e.response

file is present in bucket

In [126]:
is_present

True

In [127]:
s3.head_object(Bucket = "futureprojectbucket",Key = "file")

{'ResponseMetadata': {'RequestId': '9D0620XVCZ6PJD08',
  'HostId': 'ZpmmsQuxSrGAEv3OIDk6e955c+NgXswnoh2T1Y0+JaftCa7I7gcOiHr4euaXPK0NgsEIpD9QQr/qLJQNkAHQ2CS/1wfW1IwO',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amz-id-2': 'ZpmmsQuxSrGAEv3OIDk6e955c+NgXswnoh2T1Y0+JaftCa7I7gcOiHr4euaXPK0NgsEIpD9QQr/qLJQNkAHQ2CS/1wfW1IwO',
   'x-amz-request-id': '9D0620XVCZ6PJD08',
   'date': 'Sun, 07 Jun 2026 07:14:21 GMT',
   'last-modified': 'Sun, 07 Jun 2026 06:34:57 GMT',
   'etag': '"09b2ac1a40440b593229eaca43ea77cc"',
   'x-amz-server-side-encryption': 'AES256',
   'accept-ranges': 'bytes',
   'content-type': 'binary/octet-stream',
   'content-length': '66',
   'server': 'AmazonS3'},
  'RetryAttempts': 0},
 'AcceptRanges': 'bytes',
 'LastModified': datetime.datetime(2026, 6, 7, 6, 34, 57, tzinfo=tzutc()),
 'ContentLength': 66,
 'ETag': '"09b2ac1a40440b593229eaca43ea77cc"',
 'ContentType': 'binary/octet-stream',
 'ServerSideEncryption': 'AES256',
 'Metadata': {}}

In [129]:
s3.delete_object(Bucket = "futureprojectbucket",Key = "file")

{'ResponseMetadata': {'RequestId': 'ME1TECJ2X10WBPR1',
  'HostId': 'RFeNpQIoHZTqADForN4ssl2ZoIlu2up93RBgGJrhLL8ZhOYac2KL/+o1OD7vPdTcnqee/WbHL0I=',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': 'RFeNpQIoHZTqADForN4ssl2ZoIlu2up93RBgGJrhLL8ZhOYac2KL/+o1OD7vPdTcnqee/WbHL0I=',
   'x-amz-request-id': 'ME1TECJ2X10WBPR1',
   'date': 'Sun, 07 Jun 2026 07:15:38 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}

In [130]:
s3.delete_bucket(Bucket = "futureprojectbucket")

{'ResponseMetadata': {'RequestId': '8VTF5JMRP0S997WX',
  'HostId': 'eSSSh0SxkPKjv5V7QIiAqJpkyeFMlGc6G2bzy24XDXggTi+6G+zO2/gvvTIZy5MA3lnfsDQCbvS8g34GPRoPevn9t+7yYbap',
  'HTTPStatusCode': 204,
  'HTTPHeaders': {'x-amz-id-2': 'eSSSh0SxkPKjv5V7QIiAqJpkyeFMlGc6G2bzy24XDXggTi+6G+zO2/gvvTIZy5MA3lnfsDQCbvS8g34GPRoPevn9t+7yYbap',
   'x-amz-request-id': '8VTF5JMRP0S997WX',
   'date': 'Sun, 07 Jun 2026 07:16:15 GMT',
   'server': 'AmazonS3'},
  'RetryAttempts': 0}}