In [7]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv("Churn.csv")

In [9]:
data.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [10]:
data.drop("customerID",axis=1,inplace=True)

In [11]:
data["TotalCharges"] = pd.to_numeric(data["TotalCharges"], errors = "coerce")

In [12]:
data["TotalCharges"].dtype

dtype('float64')

In [13]:
data["TotalCharges"].fillna(0,inplace = True)

In [14]:
data["SeniorCitizen"]=data["SeniorCitizen"].map({1:"Yes",0:"No"})

In [15]:
data["Churn"] = data["Churn"].map({"Yes":1,"No":0})

In [16]:
x = data.drop("Churn",axis=1)
y = data["Churn"]

In [17]:
numric_features = [column  for column in data.columns if data[column].dtype!="O"]
cat_features = [column  for column in data.columns if data[column].dtype=="O"]

In [19]:
numric_features.remove("Churn")

In [20]:
numric_features

['tenure', 'MonthlyCharges', 'TotalCharges']

In [21]:
cat_features

['gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod']

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier

In [3]:
models = {
    "LogisticRegression":LogisticRegression(),
    "SVC":SVC(),
    "DecisionTreeClassifier":DecisionTreeClassifier(),
    "randomforestclassifier":RandomForestClassifier(),
    "adaboostclassifier":AdaBoostClassifier(),
    "xgboostclassifier":XGBClassifier()

}

In [32]:
import importlib
import model_testing

importlib.reload(model_testing)

In [33]:
from model_testing import evaluate_model

In [26]:
report = evaluate_model(x=x,y=y,models=models,numeric_features=numric_features,categorical_features=cat_features)

LogisticRegression
model performance for test Data 	- Accuracy 0.8126
- Confusion_matrix [[1154  128]
 [ 202  277]]
- precision0.6840
- f1 0.6267
- Recall0.5783
Classfication_report
              precision    recall  f1-score   support

           0       0.85      0.90      0.87      1282
           1       0.68      0.58      0.63       479

    accuracy                           0.81      1761
   macro avg       0.77      0.74      0.75      1761
weighted avg       0.81      0.81      0.81      1761

SVC
model performance for test Data 	- Accuracy 0.8047
- Confusion_matrix [[1182  100]
 [ 244  235]]
- precision0.7015
- f1 0.5774
- Recall0.4906
Classfication_report
              precision    recall  f1-score   support

           0       0.83      0.92      0.87      1282
           1       0.70      0.49      0.58       479

    accuracy                           0.80      1761
   macro avg       0.77      0.71      0.73      1761
weighted avg       0.79      0.80      0.79      1761

DecisionTreeClassifier
model performance for test Data 	- Accuracy 0.7269
- Confusion_matrix [[1048  234]
 [ 247  232]]
- precision0.4979
- f1 0.4910
- Recall0.4843
Classfication_report
              precision    recall  f1-score   support

           0       0.81      0.82      0.81      1282
           1       0.50      0.48      0.49       479

    accuracy                           0.73      1761
   macro avg       0.65      0.65      0.65      1761
weighted avg       0.72      0.73      0.73      1761

randomforestclassifier
model performance for test Data 	- Accuracy 0.7927
- Confusion_matrix [[1171  111]
 [ 254  225]]
- precision0.6696
- f1 0.5521
- Recall0.4697
Classfication_report
              precision    recall  f1-score   support

           0       0.82      0.91      0.87      1282
           1       0.67      0.47      0.55       479

    accuracy                           0.79      1761
   macro avg       0.75      0.69      0.71      1761
weighted avg       0.78      0.79      0.78      1761

adaboostclassifier
model performance for test Data 	- Accuracy 0.7984
- Confusion_matrix [[1152  130]
 [ 225  254]]
- precision0.6615
- f1 0.5886
- Recall0.5303
Classfication_report
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1282
           1       0.66      0.53      0.59       479

    accuracy                           0.80      1761
   macro avg       0.75      0.71      0.73      1761
weighted avg       0.79      0.80      0.79      1761

xgboostclassifier
model performance for test Data 	- Accuracy 0.7859
- Confusion_matrix [[1140  142]
 [ 235  244]]
- precision0.6321
- f1 0.5642
- Recall0.5094
Classfication_report
              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1282
           1       0.63      0.51      0.56       479

    accuracy                           0.79      1761
   macro avg       0.73      0.70      0.71      1761
weighted avg       0.78      0.79      0.78      1761

In [ ]:
report# before applying in techinques logistic regression performed best.

                    Model  Test_Accuracy  Train_Accuracy
0      LogisticRegression       0.812606        0.803673
1                     SVC       0.804656        0.814086
2  DecisionTreeClassifier       0.726860        0.998485
3  randomforestclassifier       0.792731        0.998485
4      adaboostclassifier       0.798410        0.808406
5       xgboostclassifier       0.785917        0.932791

In [34]:
# after applying smote 

report_smote = evaluate_model(x=x,y=y,models=models,numeric_features=numric_features,categorical_features=cat_features)

LogisticRegression
model performance for test Data 	- Accuracy 0.7547
- Confusion_matrix [[939 343]
 [ 89 390]]
- precision0.5321
- f1 0.6436
- Recall0.8142
Classfication_report
              precision    recall  f1-score   support

           0       0.91      0.73      0.81      1282
           1       0.53      0.81      0.64       479

    accuracy                           0.75      1761
   macro avg       0.72      0.77      0.73      1761
weighted avg       0.81      0.75      0.77      1761

SVC
model performance for test Data 	- Accuracy 0.7677
- Confusion_matrix [[983 299]
 [110 369]]
- precision0.5524
- f1 0.6434
- Recall0.7704
Classfication_report
              precision    recall  f1-score   support

           0       0.90      0.77      0.83      1282
           1       0.55      0.77      0.64       479

    accuracy                           0.77      1761
   macro avg       0.73      0.77      0.74      1761
weighted avg       0.80      0.77      0.78      1761

DecisionTreeClassifier
model performance for test Data 	- Accuracy 0.7382
- Confusion_matrix [[1044  238]
 [ 223  256]]
- precision0.5182
- f1 0.5262
- Recall0.5344
Classfication_report
              precision    recall  f1-score   support

           0       0.82      0.81      0.82      1282
           1       0.52      0.53      0.53       479

    accuracy                           0.74      1761
   macro avg       0.67      0.67      0.67      1761
weighted avg       0.74      0.74      0.74      1761

randomforestclassifier
model performance for test Data 	- Accuracy 0.7814
- Confusion_matrix [[1101  181]
 [ 204  275]]
- precision0.6031
- f1 0.5882
- Recall0.5741
Classfication_report
              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1282
           1       0.60      0.57      0.59       479

    accuracy                           0.78      1761
   macro avg       0.72      0.72      0.72      1761
weighted avg       0.78      0.78      0.78      1761

adaboostclassifier
model performance for test Data 	- Accuracy 0.7700
- Confusion_matrix [[980 302]
 [103 376]]
- precision0.5546
- f1 0.6500
- Recall0.7850
Classfication_report
              precision    recall  f1-score   support

           0       0.90      0.76      0.83      1282
           1       0.55      0.78      0.65       479

    accuracy                           0.77      1761
   macro avg       0.73      0.77      0.74      1761
weighted avg       0.81      0.77      0.78      1761

xgboostclassifier
model performance for test Data 	- Accuracy 0.7956
- Confusion_matrix [[1122  160]
 [ 200  279]]
- precision0.6355
- f1 0.6078
- Recall0.5825
Classfication_report
              precision    recall  f1-score   support

           0       0.85      0.88      0.86      1282
           1       0.64      0.58      0.61       479

    accuracy                           0.80      1761
   macro avg       0.74      0.73      0.73      1761
weighted avg       0.79      0.80      0.79      1761

In [35]:
report # after applying smote

                    Model  Test_Accuracy  Train_Accuracy
0      LogisticRegression       0.812606        0.803673
1                     SVC       0.804656        0.814086
2  DecisionTreeClassifier       0.726860        0.998485
3  randomforestclassifier       0.792731        0.998485
4      adaboostclassifier       0.798410        0.808406
5       xgboostclassifier       0.785917        0.932791

In [41]:
from sklearn.model_selection import train_test_split
from model_testing import preprocessor
from imblearn.pipeline import Pipeline as imblearnPipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection  import cross_val_score
import optuna
import optuna.logging
import warnings

In [50]:
# hyper paramater tuning using bayesian optimization, xgboost classifier

warnings.filterwarnings('ignore')

optuna.logging.set_verbosity(optuna.logging.ERROR)

def objective(trail):

    x_train,x_test,y_train,y_test = train_test_split(x,y)

    preprocessing = preprocessor(numeric_features=numric_features,categorical_features=cat_features)


    params = {
        "n_estimators":trail.suggest_int("n_estimators",50,400,step = 50),
        "max_depth":trail.suggest_int("max_depth",3,7),
        "learning_rate":trail.suggest_float("learning_rate",0.01,0.2),
        "subsample":trail.suggest_float("subsample",0.6,0.9),
        "colsample_bytree":trail.suggest_float("colsample_bytree",0.6,0.9),
    }

    model = XGBClassifier(**params)

    training_pipeline = imblearnPipeline([
        ("preprocessor",preprocessing),
        ("smote",SMOTE(random_state=42)),
        ("model",model)
    ])

    score = cross_val_score(training_pipeline,x_train,y_train,cv = 5, scoring="accuracy").mean()

    return score

study = optuna.create_study(direction="maximize")

study.optimize(objective,n_trials=100)

In [51]:
print(f"Best parameters, {study.best_params}")
print(f"Best value, {study.best_value}")

Best parameters, {'n_estimators': 350, 'max_depth': 3, 'learning_rate': 0.13448035395899086, 'subsample': 0.8147493301518829, 'colsample_bytree': 0.8265737183989192}
Best value, 0.7959119936355036

In [46]:
best_params = study.best_params

In [47]:
best_params

{'n_estimators': 50,
 'max_depth': 3,
 'learning_rate': 0.016108908906629638,
 'subsample': 0.8629830992909773,
 'colsample_bytree': 0.8889966919939262}

In [48]:
model_after_byperprameter_tuning = {
    "xgboost classifier":XGBClassifier(**best_params)
}

In [49]:
report = evaluate_model(x=x,y=y,models=model_after_byperprameter_tuning,numeric_features=numric_features,categorical_features=cat_features)

xgboost classifier
model performance for test Data 	- Accuracy 0.7411
- Confusion_matrix [[896 386]
 [ 70 409]]
- precision0.5145
- f1 0.6421
- Recall0.8539
Classfication_report
              precision    recall  f1-score   support

           0       0.93      0.70      0.80      1282
           1       0.51      0.85      0.64       479

    accuracy                           0.74      1761
   macro avg       0.72      0.78      0.72      1761
weighted avg       0.82      0.74      0.75      1761